spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vector_service
    username: root
    password: root
  mail:
    host: smtp.gmail.com
    port: 587
    username: javafortest2024@gmail.com
    password: rqinchnngheeexum
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath*:db/change-log.xml
server:
  port: 8080

logging:
  level:
    root: info
    vector: info
  file:
    name: C:\\Users\\hovoe\\IdeaProjects\\Java 2025 Spring\\vector-service\\logs\\application.log
  logback:
    rollingpolicy:
      max-file-size: 3MB
vector-service:
  picture:
    upload:
      directory: C:\\Users\hovoe\\IdeaProjects\\Java 2025 Spring\\vector-service\\upload